### ISSUE TITLE
New contributor

### ISSUE THREAD

**Issue by jypelle** [grafadruid/go-druid#1]
Bonjour,

Je viens de forker votre projet pour ajouter la notion de *Task* nécessaire pour lancer une ingestion de données en mode batch. J'aimerai bien contribuer directement plutôt que via des PR du fait qu'en go, ça n'est pas la panacée de faire une PR à partir d'un fork (find/replace à faire dans les imports et dans go.mod au préalable). Serait-il donc possible de m'ajouter au projet ? Au besoin, j'effectuerai mes ajouts dans une branche séparée et passerai ensuite par une PR pour l'intégration à master. Qu'en pensez-vous ?

**Comment by jbguerraz** [comment]
Bonjour @jypelle 
Avec plaisir! Merci et bienvenue :1st_place_medal: 
Pour le moment, nous avons choisi de découper les services en suivant le découpage de Druid: https://druid.apache.org/docs/latest/operations/api-reference.html
Un fichier par "server" qui expose ses services, tel que `common.go` et `query.go`; selon ce principe il conviendrait de nommer le fichier de ce "server" `master.go`, pour le sous-repertoire, plutôt que `model`, peut-être `tasks` ?
Nous pouvons revoir ce découpage! On en discutait encore tout à l'heure. N'hésites pas à nous rejoindre sur https://grafadruid.slack.com
Note: si l'anglais te conviens, c'est peut-être mieux de continuer en anglais afin de s'ouvrir au plus grand nombre :)

**Comment by jbguerraz** [comment]
@jypelle peux-être pouvons-nous fermer cette issue ?

**Comment by jypelle** [comment]
Désolé pour la réponse tardive. Suite à un changement de stratégie, mon employeur a décidé de ne pas partir sur druid pour nos futurs devs. C'est donc avec regret que je vais devoir décliner l'invitation car je n'aurais malheureusement pas le temps nécessaire pour contribuer efficacement.

**Comment by jbguerraz** [comment]
Pas de souci @jypelle 
Par curiosité, pourquoi pas Druid ? quelle technologie à la place ? :)
