### ISSUE TITLE
Intervals could be optional

### ISSUE THREAD

**Issue by jbguerraz** [grafadruid/go-druid#14]
### Error 1/3

`{"context":{"a":"a"},"dataSource":{"name":"wikipedia","type":"table"},"queryType":"dataSourceMetadata"}` is failing because `intervals` is optional for [dataSourceMetadata](https://druid.apache.org/docs/latest/querying/datasourcemetadataquery.html). 

The `intervals.Load` in [`builder/query/query.go#69`](https://github.com/grafadruid/go-druid/blob/captureErr/builder/query/query.go#L69) we do a Load with empty `[]byte` which causes JSON Umarshall to fail with the following error `Load failed, unexpected end of JSON input `. Tackle it using a different PR?

_Originally posted by @vigith in https://github.com/grafadruid/go-druid/issues/13#issuecomment-766404807_

**Comment by vigith** [comment]
should we check the length of `data []byte` and return an empty instance of `NewIntervals()`, if len == 0?

**Comment by vigith** [comment]
`if tmp.Intervals != nil {` is a better check that `len(..) == 0`
