### ISSUE TITLE
Base interval 

### ISSUE THREAD

**Issue by vigith** [grafadruid/go-druid#8]
I see and error `json: cannot unmarshal object into Go struct field .intervals of type []types.Interval` in `builder/query/scan.go` if the interval passed to `Base` is a JSON object.

```json
  "intervals": {
    "type": "intervals",
    "intervals": [
      "-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"
    ]
  }
```

The reason for this is because `builder/types/intervals.go` users strings and not structured types 
```go
// Interval represents a druid interval.
type Interval struct {
	StartTime time.Time
	EndTime   time.Time
}
```

**Comment by jbguerraz** [comment]
Fixed by #9
